# Generated by Django 4.0.4 on 2022-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('in_review', 'In_review'), ('active', 'Active')], default='in_review', max_length=10),
        ),
    ]
