# Generated by Django 4.0.4 on 2022-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sequence',
            field=models.SmallIntegerField(help_text='This is the order in which the lessons should be watched.', unique=True),
        ),
    ]
