# Generated by Django 4.0.4 on 2022-06-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_price_alter_lesson_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sequence',
            field=models.PositiveSmallIntegerField(help_text="This is the order in which the lessons should be watched.<br />Note: Two lessons can't have the same sequence", unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('in_review', 'In_review'), ('active', 'Active')], default='in_review', help_text='Change to active if you want users to view it', max_length=10),
        ),
    ]
