# Generated by Django 4.0.4 on 2022-06-07 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_description_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('video_file', models.FileField(blank='True', null=True, upload_to='course_videos')),
                ('sequence', models.PositiveSmallIntegerField(help_text="This is the order in which the videos should be watched.<br />Note: Two videos can't have the same sequence", unique=True)),
                ('status', models.CharField(choices=[('in_review', 'In_review'), ('active', 'Active')], default='in_review', help_text='Change to active if you want users to view it', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
