# Generated by Django 4.0.4 on 2022-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_image',
            field=models.FileField(default=True, upload_to='poster_images'),
            preserve_default=False,
        ),
    ]
